#ifndef _BLE_AUDIO_FLAGS_H_
#define _BLE_AUDIO_FLAGS_H_

#define LE_AUDIO_DEBUG            1
#define LE_AUDIO_USE_EXT_SERVER   0

#define MAX_BLE_LINK_NUM 2
#define MAX_BLE_SRV_NUM 16

#define LE_AUDIO_PACS_SUPPORT 1
#define LE_AUDIO_ASCS_SUPPORT 1
#define LE_AUDIO_BASS_SUPPORT 1

#define LE_AUDIO_VCS_SUPPORT 1
#define LE_AUDIO_VOCS_SUPPORT 1
#define LE_AUDIO_AICS_SUPPORT 1
#define LE_AUDIO_AICS_NUM 1
#define LE_AUDIO_MICS_SUPPORT 1

#define LE_AUDIO_CSIS_SUPPORT 1
#define LE_AUDIO_CAS_SUPPORT 1

#define LE_AUDIO_TBS_SUPPORT 1
#define LE_AUDIO_TMAS_SUPPORT 1

#define LE_AUDIO_MCS_SERV_SUPPORT  1
#define LE_AUDIO_OTS_SERV_SUPPORT  1

#define LE_AUDIO_CAP_SUPPORT 1
#define LE_AUDIO_BAP_SUPPORT 1

#define LE_AUDIO_PACS_CLIENT_SUPPORT 1
#define LE_AUDIO_ASCS_CLIENT_SUPPORT 1
#define LE_AUDIO_BASS_CLIENT_SUPPORT 1
#define LE_AUDIO_MCS_CLIENT_SUPPORT  1
#define LE_AUDIO_OTS_CLIENT_SUPPORT  1

#define LE_AUDIO_VCS_CLIENT_SUPPORT 1
#define LE_AUDIO_VOCS_CLIENT_SUPPORT 1
#define LE_AUDIO_AICS_CLIENT_SUPPORT 1
#define LE_AUDIO_MICS_CLIENT_SUPPORT 1

#define LE_AUDIO_CSIS_CLIENT_SUPPORT 1
#define LE_AUDIO_TBS_CLIENT_SUPPORT 1
#define LE_AUDIO_TMAP_CLIENT_SUPPORT 1

#define LE_AUDIO_BROADCAST_SOURCE_ROLE    1
#define LE_AUDIO_BROADCAST_SINK_ROLE      1
#define LE_AUDIO_SCAN_DELEGATOR_ROLE      1
#define LE_AUDIO_BROADCAST_ASSISTANT_ROLE 1

#define LE_AUDIO_BASE_DATA_GENERATE (LE_AUDIO_BROADCAST_SOURCE_ROLE)
#define LE_AUDIO_BASE_DATA_PARSE    (LE_AUDIO_BROADCAST_SINK_ROLE || LE_AUDIO_BROADCAST_ASSISTANT_ROLE)

#endif
